### PR TITLE
Generic Custom Branding

### PR DESCRIPTION
**Pull request by dpose**
Generic Custom Branding

### CODE REVIEW

**Comment by sduenas** [comment]
This PR is very similar to #1 . Why do we need it?

**Comment by acs** [comment]
@sduenas they are for different branches.

**Comment by sduenas** [comment]
> @sduenas they are for different branches. 

I saw it but if you want to have the same commit in different branches, this is not the way. Push the commit to a branch and then merge that branch or use `cherry pick`.

**Comment by acs** [comment]
Yes, but it is not exactly the same. In any case, one of the PR is not going to be used so, we can just close it! I am going to do it right now. Thanks for the follow up!

**Comment by acs** [comment]
@dpose in order to integrate the branding to a 4.x branch, it is done in the branding-4.x and then this branch is merged in the 4.x branch which should include this feature. In the commits of the current integration-4.4.1-public branch

```
(acs@dellx) (integration-4.4.1-public $% u=) ~/devel/kibiter $ git log | grep brand
    Merge branch 'branding-4.x' into integration-4.4.1-public
```

So in order to improve the branding, it must be done in 'branding-4.x' and also, for supporting it in master branch (in sync with Kibana master branch), in 'branding' branch. And then merge these branches when needed the feature.

So I will review your proposal changes and integrate them in this 'branding-4.x' and 'branding' branches and then, remerge the 'branding-4.x' in 'integration-4.4.1-public'.

**Comment by acs** [comment]
@dpose already added the changes from branding-4.x branch.

https://github.com/grimoirelab/kibiter/commit/9647e524f901c14bfc18bb79bfcb653810f9f766

Thank you!

**Pull request closed without merging**
